version: "3.9"
services:
  auth:
    container_name: irc_auth
    build:
      context: .
      dockerfile: auth.Dockerfile
    ports:
      - 4444:4444
    restart: always
  enc:
    container_name: irc_enc
    build:
      context: .
      dockerfile: enc.Dockerfile
    ports:
      - 4443:4443
    restart: always

  irc:
    container_name: irc_server
    build:
      context: .
      dockerfile: irc.Dockerfile
    ports:
      - 1234:8784
        #depends_on:
        #- auth
        #- enc
    restart: always
    env_file: irc.env
       

  client:
    container_name: irc_client
    build:
      context: .
      dockerfile: client.Dockerfile

networks:
  default:
    name: irc-np
